# src/config/constants.py

# Column names
COL_FUND_NAME = "FUND NAME"
COL_DATETIME = "DATETIME"
COL_PRICE = "PRICE"
COL_SYMBOL = "SYMBOL"
COL_MARKET_VALUE = "MARKET VALUE"
COL_REALIZED_PL = "REALISED P/L"
COL_PRICE_FUND = "PRICE_FUND"
COL_PRICE_REF = "PRICE_REF"
COL_PRICE_DIFF = "PRICE_DIFF"

# Join keys
JOIN_KEYS = [COL_DATETIME, COL_SYMBOL]